### ISSUE TITLE
1. Get all notes on the current page

### ISSUE THREAD

**Issue by jinpark** [JayParkOnGithub/XiaomiNoteExporter#1]
Only get the results that are shown in the page

- [x] figure out how to get the 8(or so) note elements on the note list sidebar
- [ ] figure out how to select the date on each sidebar note element
- [ ] figure out how to convert date string in sidebar note element to epoch timestamp
- [ ] figure out how to click each sidebar note element to trigger changing of the main note page/element
- [ ] figure out how to select the title on main note element
- [ ] figure out how to select the body on main note element
- [ ] append timestamp, title and body into an array

Result should be saved in a variable that looks like 

```yaml
[
{
'timestamp': 1651366295814,
'title': 'this is a title that can also be blank',
'body': '<p>http://m.yes24.com/Goods/Detail/91231989</p><p><br></p><p>Green course</p><p><br></p><p>http://m.yes24.com/Goods/Detail/66924896</p>'
},
{
'timestamp': 1651366295815,
'title': 'this is another title',
'body': '<p>this is a body</b>'
},
]
```
